// Mocks generated by Mockito 5.4.4 from annotations
// in practice1_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:practice1_app/core/error/failure.dart' as _i7;
import 'package:practice1_app/core/network/client.dart' as _i4;
import 'package:practice1_app/features/posts/data/datasources/remote/post_remote_data_source.dart'
    as _i10;
import 'package:practice1_app/features/posts/data/models/comment_model.dart'
    as _i12;
import 'package:practice1_app/features/posts/data/models/post_model.dart'
    as _i11;
import 'package:practice1_app/features/posts/domain/entities/comment_entity.dart'
    as _i9;
import 'package:practice1_app/features/posts/domain/entities/post_entity.dart'
    as _i8;
import 'package:practice1_app/features/posts/domain/repositories/post_repository.dart'
    as _i6;
import 'package:practice1_app/features/posts/domain/usecases/get_comments_by_post_id.dart'
    as _i14;
import 'package:practice1_app/features/posts/domain/usecases/get_posts.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i4.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<dynamic>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i6.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i8.PostEntity>>> getPosts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i7.RemoteFailure, List<_i8.PostEntity>>>.value(
            _FakeEither_1<_i7.RemoteFailure, List<_i8.PostEntity>>(
          this,
          Invocation.method(
            #getPosts,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i8.PostEntity>>>);

  @override
  _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i9.CommentEntity>>>
      getCommentsByPostId(int? postId) => (super.noSuchMethod(
            Invocation.method(
              #getCommentsByPostId,
              [postId],
            ),
            returnValue: _i5.Future<
                    _i3
                    .Either<_i7.RemoteFailure, List<_i9.CommentEntity>>>.value(
                _FakeEither_1<_i7.RemoteFailure, List<_i9.CommentEntity>>(
              this,
              Invocation.method(
                #getCommentsByPostId,
                [postId],
              ),
            )),
          ) as _i5
              .Future<_i3.Either<_i7.RemoteFailure, List<_i9.CommentEntity>>>);

  @override
  _i5.Future<_i3.Either<_i7.LocalFailure, List<_i8.PostEntity>>>
      getLocalPosts() => (super.noSuchMethod(
            Invocation.method(
              #getLocalPosts,
              [],
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i7.LocalFailure, List<_i8.PostEntity>>>.value(
                _FakeEither_1<_i7.LocalFailure, List<_i8.PostEntity>>(
              this,
              Invocation.method(
                #getLocalPosts,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i7.LocalFailure, List<_i8.PostEntity>>>);

  @override
  _i5.Future<_i3.Either<_i7.LocalFailure, bool>> savePosts(
          List<_i8.PostEntity>? posts) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePosts,
          [posts],
        ),
        returnValue: _i5.Future<_i3.Either<_i7.LocalFailure, bool>>.value(
            _FakeEither_1<_i7.LocalFailure, bool>(
          this,
          Invocation.method(
            #savePosts,
            [posts],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i7.LocalFailure, bool>>);
}

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i10.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i11.PostModel>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i5.Future<List<_i11.PostModel>>.value(<_i11.PostModel>[]),
      ) as _i5.Future<List<_i11.PostModel>>);

  @override
  _i5.Future<List<_i12.CommentModel>> getCommentsByPostId(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommentsByPostId,
          [postId],
        ),
        returnValue:
            _i5.Future<List<_i12.CommentModel>>.value(<_i12.CommentModel>[]),
      ) as _i5.Future<List<_i12.CommentModel>>);
}

/// A class which mocks [GetPostsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPostsUsecase extends _i1.Mock implements _i13.GetPostsUsecase {
  MockGetPostsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i8.PostEntity>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i7.RemoteFailure, List<_i8.PostEntity>>>.value(
            _FakeEither_1<_i7.RemoteFailure, List<_i8.PostEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i8.PostEntity>>>);
}

/// A class which mocks [GetCommentsByPostIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCommentsByPostIdUseCase extends _i1.Mock
    implements _i14.GetCommentsByPostIdUseCase {
  MockGetCommentsByPostIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i9.CommentEntity>>> execute(
          {required int? postId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#postId: postId},
        ),
        returnValue: _i5.Future<
                _i3.Either<_i7.RemoteFailure, List<_i9.CommentEntity>>>.value(
            _FakeEither_1<_i7.RemoteFailure, List<_i9.CommentEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
            {#postId: postId},
          ),
        )),
      ) as _i5.Future<_i3.Either<_i7.RemoteFailure, List<_i9.CommentEntity>>>);
}
